config/routes.rb
Laboratory::Application.routes.draw do

  resources :application_user_roles

  devise_for :users

  namespace :admin do
    resources :users
  end

  resources :organizations

  resources :contact_mechanism_purpose_types

  resources :role_types

  resources :contact_mechanism_types

  resources :postal_addresses

  resources :geographic_boundary_association_types

  resources :geographic_boundaries do
    collection do
      get :countries
      get :postal_codes
      get :cities
      get :suburbs
    end
  end

  resources :electronic_addresses, :only => [:index]

  resources :geographic_boundary_types

  resources :training_class_types

  resources :languages

  resources :marital_status_types

  resources :person_status_types

  resources :categories

  resources :category_types

  resources :physical_characteristic_types

  resources :unit_of_measures

  resources :diagnosis_types

  resources :patient_roles

  resources :employee_roles

  resources :customer_roles

  resources :payor_roles

  resources :contact_roles

  resources :child_roles

  resources :parent_roles

  resources :genetic_counselor_roles

  resources :doctor_roles

  resources :nurse_roles

  resources :gender_types

  resources :genders

  resources :people

  get "welcome/index"     # generate the route for the welcome page
  root 'welcome#index'    # make the welcome page the root of the application "/"

end

app/controllers/physical_characteristic_types_controller.rb
class PhysicalCharacteristicTypesController < ApplicationController
  before_action :set_physical_characteristic_type, only: [:show, :edit, :update, :destroy]

  # GET /physical_characteristic_types
  # GET /physical_characteristic_types.json
  def index
    @physical_characteristic_types = PhysicalCharacteristicType.all
  end

  # GET /physical_characteristic_types/1
  # GET /physical_characteristic_types/1.json
  def show
  end

  # GET /physical_characteristic_types/new
  def new
    @physical_characteristic_type = PhysicalCharacteristicType.new
  end

  # GET /physical_characteristic_types/1/edit
  def edit
  end

  # POST /physical_characteristic_types
  # POST /physical_characteristic_types.json
  def create
    @physical_characteristic_type = PhysicalCharacteristicType.new(physical_characteristic_type_params)

    respond_to do |format|
      if @physical_characteristic_type.save
        format.html { redirect_to @physical_characteristic_type, notice: "#{I18n.t('physical_characteristic_type.model_name').titleize} #{I18n.t('forms.flash_created')}" }
        format.json { render action: 'show', status: :created, location: @physical_characteristic_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @physical_characteristic_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physical_characteristic_types/1
  # PATCH/PUT /physical_characteristic_types/1.json
  def update
    respond_to do |format|
      if @physical_characteristic_type.update(physical_characteristic_type_params)
        format.html { redirect_to @physical_characteristic_type, notice: "#{I18n.t('physical_characteristic_type.model_name').titleize} #{I18n.t('forms.flash_updated')}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @physical_characteristic_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physical_characteristic_types/1
  # DELETE /physical_characteristic_types/1.json
  def destroy
    @physical_characteristic_type.destroy
    respond_to do |format|
      format.html { redirect_to physical_characteristic_types_url, notice: "#{I18n.t('physical_characteristic_type.model_name').titleize} #{I18n.t('forms.flash_destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physical_characteristic_type
      @physical_characteristic_type = PhysicalCharacteristicType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physical_characteristic_type_params
      params.require(:physical_characteristic_type).permit(:name, :description)
    end
end

app/helpers/physical_characteristic_types_helper.rb
module PhysicalCharacteristicTypesHelper
end

app/views/physical_characteristic_types/_form.html.haml
= simple_form_for @physical_characteristic_type, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification

  %legend
    = controller.action_name.capitalize
    =t('physical_characteristic_type.model_name')


  .form-inputs
    = f.input :name, label: t('physical_characteristic_type.name')
    = f.input :description, label: t('physical_characteristic_type.description')

  .form-actions
    = f.submit t('actions.save'), class: 'btn btn-primary btn-mini'
    = link_to t('actions.back'),physical_characteristic_types_path, class: 'btn btn-mini'

app/views/physical_characteristic_types/edit.html.haml
= render 'form'

app/views/physical_characteristic_types/index.html.haml
%h2
  =t('physical_characteristic_type.index_heading')

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th= t('physical_characteristic_type.name')
      %th= t('physical_characteristic_type.description')
      -if can? [:update, :destroy], :physical_characteristic_type
        %th.actions
          Actions

  %tbody
  -@physical_characteristic_types.each do |physical_characteristic_type|
    %tr{:id => "physical_characteristic_type_#{physical_characteristic_type.id}"}
      %td= link_to physical_characteristic_type.name, physical_characteristic_type
      %td= physical_characteristic_type.description
      -if can? [:update, :destroy], :physical_characteristic_type
        %td.actions
          -if can? [:update], :physical_characteristic_type
            = link_to t('actions.edit'), edit_physical_characteristic_type_path(physical_characteristic_type), class: "btn btn-mini"
          -if can? [:destroy], :physical_characteristic_type
            = link_to t('actions.destroy'), physical_characteristic_type, method: :delete, data: { confirm: t('actions.are_you_sure') }, class: "btn btn-mini btn-danger"

-if can? [:create], :physical_characteristic_type
  %br
  = link_to t('actions.new_record', record: t('physical_characteristic_type.model_name')), new_physical_characteristic_type_path, class: "btn btn-small btn-success"

app/views/physical_characteristic_types/new.html.haml
= render 'form'

app/views/physical_characteristic_types/show.html.haml
%h2
  =t('forms.details')
  =" - "
  = @physical_characteristic_type.name
%div#physical_characteristic_type
  %dl.dl-horizontal
    %dt= t('physical_characteristic_type.name')
    %dd= @physical_characteristic_type.name
    %dt= t('physical_characteristic_type.description')
    %dd= @physical_characteristic_type.description
  
  -if can? :update, @physical_characteristic_type
    = link_to t('actions.edit'), edit_physical_characteristic_type_path(@physical_characteristic_type), class: 'btn btn-primary btn-mini'
  = link_to t('actions.back'), physical_characteristic_types_path, class: 'btn btn-mini'