config/routes.rb
Laboratory::Application.routes.draw do

  resources :application_user_roles

  devise_for :users

  namespace :admin do
    resources :users
  end

  resources :organizations

  resources :contact_mechanism_purpose_types

  resources :role_types

  resources :contact_mechanism_types

  resources :postal_addresses

  resources :geographic_boundary_association_types

  resources :geographic_boundaries do
    collection do
      get :countries
      get :postal_codes
      get :cities
      get :suburbs
    end
  end

  resources :electronic_addresses, :only => [:index]

  resources :geographic_boundary_types

  resources :training_class_types

  resources :languages

  resources :marital_status_types

  resources :person_status_types

  resources :categories

  resources :category_types

  resources :physical_characteristic_types

  resources :unit_of_measures

  resources :diagnosis_types

  resources :patient_roles

  resources :employee_roles

  resources :customer_roles

  resources :payor_roles

  resources :contact_roles

  resources :child_roles

  resources :parent_roles

  resources :genetic_counselor_roles

  resources :doctor_roles

  resources :nurse_roles

  resources :gender_types

  resources :genders

  resources :people

  get "welcome/index"     # generate the route for the welcome page
  root 'welcome#index'    # make the welcome page the root of the application "/"

end

app/models/payor_role.rb
class PayorRole < ActiveRecord::Base

  belongs_to :person

end

app/controllers/payor_roles_controller.rb
class PayorRolesController < ApplicationController
  before_action :set_payor_role, only: [:show, :edit, :update, :destroy]

  # GET /payor_roles
  # GET /payor_roles.json
  def index
    @payor_roles = PayorRole.all
  end

  # GET /payor_roles/1
  # GET /payor_roles/1.json
  def show
  end

  # GET /payor_roles/new
  def new
    @payor_role = PayorRole.new
  end

  # GET /payor_roles/1/edit
  def edit
  end

  # POST /payor_roles
  # POST /payor_roles.json
  def create
    @payor_role = PayorRole.new(payor_role_params)

    respond_to do |format|
      if @payor_role.save
        format.html { redirect_to @payor_role, notice: "#{I18n.t('payor_role.model_name').titleize} #{I18n.t('forms.flash_created')}" }
        format.json { render action: 'show', status: :created, location: @payor_role }
      else
        format.html { render action: 'new' }
        format.json { render json: @payor_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payor_roles/1
  # PATCH/PUT /payor_roles/1.json
  def update
    respond_to do |format|
      if @payor_role.update(payor_role_params)
        format.html { redirect_to @payor_role, notice: "#{I18n.t('payor_role.model_name').titleize} #{I18n.t('forms.flash_updated')}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payor_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payor_roles/1
  # DELETE /payor_roles/1.json
  def destroy
    @payor_role.destroy
    respond_to do |format|
      format.html { redirect_to payor_roles_url, notice: "#{I18n.t('payor_role.model_name').titleize} #{I18n.t('forms.flash_destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payor_role
      @payor_role = PayorRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payor_role_params
      params.require(:payor_role).permit(:person_id)
    end
end

app/helpers/payor_roles_helper.rb
module PayorRolesHelper
end

app/views/payor_roles/_form.html.haml
= simple_form_for @payor_role, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification

  %legend
    = controller.action_name.capitalize
    =t('payor_role.model_name')


  .form-inputs
    = f.input :person_id, label: t('payor_role.person_id')

  .form-actions
    = f.submit t('actions.save'), class: 'btn btn-primary btn-mini'
    = link_to t('actions.back'),payor_roles_path, class: 'btn btn-mini'

app/views/payor_roles/edit.html.haml
= render 'form'

app/views/payor_roles/index.html.haml
%h2
  =t('payor_role.index_heading')

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th
        =t('payor_role.person_id')
      %th.actions
        Actions

  %tbody
  -@payor_roles.each do |payor_role|
    %tr{:id => "payor_role_#{payor_role.id}"}

      %td= link_to payor_role.person_id, payor_role

      %td.actions
        = link_to t('actions.edit'), edit_payor_role_path(payor_role), class: "btn btn-mini"
        = link_to t('actions.destroy'), payor_role, method: :delete, data: { confirm: t('actions.are_you_sure') }, class: "btn btn-mini btn-danger"


%br

= link_to t('actions.new_record', record: t('payor_role.model_name')), new_payor_role_path, class: "btn btn-small btn-success"

app/views/payor_roles/new.html.haml
= render 'form'

app/views/payor_roles/show.html.haml
%h2
  =t('forms.details')
  =" - "
  = @payor_role.person_id
%div#payor_role
  %dl.dl-horizontal
    %dt
      =t('payor_role.person_id')
    %dd
      = @payor_role.person_id
  
  = link_to t('actions.edit'), edit_payor_role_path(@payor_role), class: 'btn btn-primary btn-mini'
  = link_to t('actions.back'), payor_roles_path, class: 'btn btn-mini'