config/routes.rb
Laboratory::Application.routes.draw do

  resources :application_user_roles

  devise_for :users

  namespace :admin do
    resources :users
  end

  resources :organizations

  resources :contact_mechanism_purpose_types

  resources :role_types

  resources :contact_mechanism_types

  resources :postal_addresses

  resources :geographic_boundary_association_types

  resources :geographic_boundaries do
    collection do
      get :countries
      get :postal_codes
      get :cities
      get :suburbs
    end
  end

  resources :electronic_addresses, :only => [:index]

  resources :geographic_boundary_types

  resources :training_class_types

  resources :languages

  resources :marital_status_types

  resources :person_status_types

  resources :categories

  resources :category_types

  resources :physical_characteristic_types

  resources :unit_of_measures

  resources :diagnosis_types

  resources :patient_roles

  resources :employee_roles

  resources :customer_roles

  resources :payor_roles

  resources :contact_roles

  resources :child_roles

  resources :parent_roles

  resources :genetic_counselor_roles

  resources :doctor_roles

  resources :nurse_roles

  resources :gender_types

  resources :genders

  resources :people

  get "welcome/index"     # generate the route for the welcome page
  root 'welcome#index'    # make the welcome page the root of the application "/"

end

app/models/employee_role.rb
class EmployeeRole < ActiveRecord::Base

  belongs_to :person

end

app/controllers/employee_roles_controller.rb
class EmployeeRolesController < ApplicationController
  before_action :set_employee_role, only: [:show, :edit, :update, :destroy]

  # GET /employee_roles
  # GET /employee_roles.json
  def index
    @employee_roles = EmployeeRole.all
  end

  # GET /employee_roles/1
  # GET /employee_roles/1.json
  def show
  end

  # GET /employee_roles/new
  def new
    @employee_role = EmployeeRole.new
  end

  # GET /employee_roles/1/edit
  def edit
  end

  # POST /employee_roles
  # POST /employee_roles.json
  def create
    @employee_role = EmployeeRole.new(employee_role_params)

    respond_to do |format|
      if @employee_role.save
        format.html { redirect_to @employee_role, notice: "#{I18n.t('employee_role.model_name').titleize} #{I18n.t('forms.flash_created')}" }
        format.json { render action: 'show', status: :created, location: @employee_role }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_roles/1
  # PATCH/PUT /employee_roles/1.json
  def update
    respond_to do |format|
      if @employee_role.update(employee_role_params)
        format.html { redirect_to @employee_role, notice: "#{I18n.t('employee_role.model_name').titleize} #{I18n.t('forms.flash_updated')}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_roles/1
  # DELETE /employee_roles/1.json
  def destroy
    @employee_role.destroy
    respond_to do |format|
      format.html { redirect_to employee_roles_url, notice: "#{I18n.t('employee_role.model_name').titleize} #{I18n.t('forms.flash_destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_role
      @employee_role = EmployeeRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_role_params
      params.require(:employee_role).permit(:person_id)
    end
end

app/helpers/employee_roles_helper.rb
module EmployeeRolesHelper
end

app/views/employee_roles/_form.html.haml
= simple_form_for @employee_role, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification

  %legend
    = controller.action_name.capitalize
    =t('employee_role.model_name')


  .form-inputs
    = f.input :person_id, label: t('employee_role.person_id')

  .form-actions
    = f.submit t('actions.save'), class: 'btn btn-primary btn-mini'
    = link_to t('actions.back'),employee_roles_path, class: 'btn btn-mini'

app/views/employee_roles/edit.html.haml
= render 'form'

app/views/employee_roles/index.html.haml
%h2
  =t('employee_role.index_heading')

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th
        =t('employee_role.person_id')
      %th.actions
        Actions

  %tbody
  -@employee_roles.each do |employee_role|
    %tr{:id => "employee_role_#{employee_role.id}"}

      %td= link_to employee_role.person_id, employee_role

      %td.actions
        = link_to t('actions.edit'), edit_employee_role_path(employee_role), class: "btn btn-mini"
        = link_to t('actions.destroy'), employee_role, method: :delete, data: { confirm: t('actions.are_you_sure') }, class: "btn btn-mini btn-danger"


%br

= link_to t('actions.new_record', record: t('employee_role.model_name')), new_employee_role_path, class: "btn btn-small btn-success"

app/views/employee_roles/new.html.haml
= render 'form'

app/views/employee_roles/show.html.haml
%h2
  =t('forms.details')
  =" - "
  = @employee_role.person_id
%div#employee_role
  %dl.dl-horizontal
    %dt
      =t('employee_role.person_id')
    %dd
      = @employee_role.person_id
  
  = link_to t('actions.edit'), edit_employee_role_path(@employee_role), class: 'btn btn-primary btn-mini'
  = link_to t('actions.back'), employee_roles_path, class: 'btn btn-mini'