config/routes.rb
Laboratory::Application.routes.draw do

  resources :application_user_roles

  devise_for :users

  namespace :admin do
    resources :users
  end

  resources :organizations

  resources :contact_mechanism_purpose_types

  resources :role_types

  resources :contact_mechanism_types

  resources :postal_addresses

  resources :geographic_boundary_association_types

  resources :geographic_boundaries do
    collection do
      get :countries
      get :postal_codes
      get :cities
      get :suburbs
    end
  end

  resources :electronic_addresses, :only => [:index]

  resources :geographic_boundary_types

  resources :training_class_types

  resources :languages

  resources :marital_status_types

  resources :person_status_types

  resources :categories

  resources :category_types

  resources :physical_characteristic_types

  resources :unit_of_measures

  resources :diagnosis_types

  resources :patient_roles

  resources :employee_roles

  resources :customer_roles

  resources :payor_roles

  resources :contact_roles

  resources :child_roles

  resources :parent_roles

  resources :genetic_counselor_roles

  resources :doctor_roles

  resources :nurse_roles

  resources :gender_types

  resources :genders

  resources :people

  get "welcome/index"     # generate the route for the welcome page
  root 'welcome#index'    # make the welcome page the root of the application "/"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :person_category_classifications
  has_many :people, -> { uniq }, through: :person_category_classifications

  belongs_to :category_type

  validates :name, presence: true
  validates :category_type_id, presence: true

end

app/models/category_type.rb
class CategoryType < ActiveRecord::Base

  # a category_type has many categories
  has_many :categories

  # validations
  validates :name, presence: true, uniqueness: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.page(params[:page]).order("name ASC")
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "#{I18n.t('category.model_name').titleize} #{I18n.t('forms.flash_created')}" }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "#{I18n.t('category.model_name').titleize} #{I18n.t('forms.flash_updated')}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "#{I18n.t('category.model_name').titleize} #{I18n.t('forms.flash_destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :category_type_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category, :html => { :class => 'form-horizontal' }) do |f|
  = f.error_notification


  %legend
    = controller.action_name.capitalize
    =t('category.model_name')

  .form-inputs
    = f.association :category_type, collection: CategoryType.order("name ASC"), label: t('category_type.model_name'), prompt: t('forms.please_select')
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit, t('actions.save'), class: 'btn btn-primary btn-small'
    = link_to t('actions.back'), categories_path, class: "btn btn-small"

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/index.html.haml
%h2
  =t('category.index_heading')

= will_paginate @categories

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th= t('category.name')
      %th= t('category.description')
      %th= t('category.category_type')
      -if can? [:update, :destroy], :category
        %th
          Actions
  %tbody
  -@categories.each do |category|
    %tr{:id => "category_#{category.id}"}
      %td= link_to category.name, category
      %td= category.description
      %td= category.category_type.name
      -if can? [:update, :destroy], :category
        %td
          -if can? :update, :category
            = link_to t('actions.edit'), edit_category_path(category), class: "btn btn-mini"
          -if can? :destroy, :category
            = link_to t('actions.destroy'), category, method: :delete, data: { confirm: t('actions.are_you_sure') }, class: "btn btn-mini btn-danger"
-if can? :create, :category
  %br
  = link_to t('actions.new_record', record: t('category.model_name')), new_category_path, class: "btn btn-small btn-success"

app/views/categories/new.html.haml
= render 'form'

app/views/categories/show.html.haml
%h2
  =t('form.details')
  =" - "
  = @category.name
%div#category
  %dl.dl-horizontal
    %dt=t('category.name')
    %dd= @category.name
    %dt=t('category.description')
    %dd= @category.description
    %dt=t('category.category_type')
    %dd= @category.category_type.name
  
  -if can? :update, @category
    = link_to t('actions.edit'), edit_category_path(@category), class: 'btn btn-primary btn-small'
  = link_to t('actions.back'), categories_path, class: 'btn btn-small'